language: go
go_import_path: github.com/Prowler-io/kubetoken
go:
  - 1.8.x
  - tip

script:
  - go list github.com/Prowler-io/kubetoken/... | grep -v vendor | xargs go test
  - go list github.com/Prowler-io/kubetoken/... | grep -v vendor | xargs go test -race
